### PR TITLE
60 fix for concat

### LINKED ISSUE #60: Check that list.concat() does not serialize the objects in the list before adding it to the resulting list
Based on https://github.com/canjs/can-list/issues/3

### PR DESCRIPTION
**Pull request by Sinjhin**
Closes #60 

Makes concat behave as expected and reference objects passed as args so that `sourceList[ 0 ] === ( sourceList.concat( [] ) )[ 0 ];`.

### CODE REVIEW

File: list/list.js [hunk 1]
```diff
@@ -781,12 +792,33 @@ assign(DefineList.prototype, {
      * newList.get(); // ['Alice', 'Bob', 'Charlie', 'Daniel', 'Eve', {f: 'Francis'}]
      * ```
      */
-    concat: function () {
-        var args = [];
-        each(makeArray(arguments), function (arg, i) {
-            args[i] = arg instanceof DefineList ? arg.get() : arg;
+    concat: function() {
+        debugger;
```
Comment (phillipskevin) [inline list/list.js]: This probably shouldn't be left in.

Comment (justinbmeyer) [inline list/list.js]: This probably means that jshint is not running on can-define.
