### PR TITLE
Fixes #353. Can-define special-keys assignment does not throw an error

### LINKED ISSUE #353: An in-range update of can-assign is breaking the build 🚨
## Version **1.3.0** of **can-assign** was just published.

<table>
  <tr>
    <th align=left>
      Branch
    </th>
    <td>
      <a href="https://github.com/canjs/can-define/compare/master...canjs:greenkeeper%2Fcan-assign-1.3.0">Build failing 🚨</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Dependency
    </th>
    <td>
      <a target=_blank href=https://github.com/canjs/can-assign>can-assign</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Current Version
    </td>
    <td>
      1.2.0
    </td>
  </tr>
  <tr>
    <th align=left>
      Type
    </td>
    <td>
      dependency
    </td>
  </tr>
</table>

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

can-assign is a direct dependency of this project, and **it is very likely causing it to break**. If other packages depend on yours, this update is probably also breaking those in turn.

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/travis-ci/push** The Travis CI build failed [Details](https://travis-ci.org/canjs/can-define/builds/402298566?utm_source=github_status&utm_medium=notification)
</details>

---

<details>
<summary>Release Notes</summary>
<strong>v1.3.0</strong>

<ul>
<li>Added 'use strict' <a class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="336405360" data-permission-text="Issue title is private" data-url="https://github.com/canjs/can-assign/issues/7" href="https://urls.greenkeeper.io/canjs/can-assign/pull/7">#7</a></li>
</ul>
</details>

<details>
<summary>Commits</summary>
<p>The new version differs by 5 commits ahead by 5, behind by 1.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/canjs/can-assign/commit/21fef16f815a7f7f051db68a0ec7b0017e1f2286"><code>21fef16</code></a> <code>1.3.0</code></li>
<li><a href="https://urls.greenkeeper.io/canjs/can-assign/commit/0623dfa97233abe212b4ba4338709f617c121288"><code>0623dfa</code></a> <code>Update version number</code></li>
<li><a href="https://urls.greenkeeper.io/canjs/can-assign/commit/74b98d05d1fced3a719087aaa8aa66654c27b47c"><code>74b98d0</code></a> <code>Merge pull request #7 from canjs/landscaper/4217-use-strict</code></li>
<li><a href="https://urls.greenkeeper.io/canjs/can-assign/commit/baa43d773917e688e24753b14a8febdd37f445ee"><code>baa43d7</code></a> <code>Merge branch 'master' into landscaper/4217-use-strict</code></li>
<li><a href="https://urls.greenkeeper.io/canjs/can-assign/commit/871d831dbbf65a7b42bef437b8c4ef64b51faaa8"><code>871d831</code></a> <code>Adds use strict. Fixes canjs/canjs#4217</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/canjs/can-assign/compare/961583c45912477faf950176d10093d01703d906...21fef16f815a7f7f051db68a0ec7b0017e1f2286">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by Aosanders**
can-define/map/map-test.js was throwing an error when testing assignment of special keys to a DefineMap object. Added check to see if property being assigned is writable; if not, the property is skipped.

Should we add a warning if someone attempts to add a special key to a DefineMap object?

### CODE REVIEW

**Comment by matthewp** [comment]
lgtm

File: can-define.js [hunk 1]
```diff
@@ -54,7 +54,11 @@ if(process.env.NODE_ENV !== 'production') {
 				value:  "set "+canReflect.getName(obj) + "."+prop
 			});
 		}
-		return Object.defineProperty(obj, prop, definition);
+    var desc = Object.getOwnPropertyDescriptor(obj, prop);
+    if(!desc || desc.writable !== false){
```
Comment (chasenlehara) [inline can-define.js]: I think it’d be just a little bit faster if this checked specifically for `undefined` instead of casting `desc`:

```js
if (desc === undefined || desc.writable !== false) {
```

Also, the indentation of these lines should be consistent with the rest of the file.

File: map/map-test.js [hunk 2]
```diff
@@ -473,18 +473,15 @@ QUnit.test("copying with assign() excludes special keys", function() {
 
 	var a = {
 		_data: {},
-		constructor: function() {},
-		__bindEvents: {},
```
Comment (chasenlehara) [inline map/map-test.js]: Were these not important to the test?

File: map/map-test.js [hunk 3]
```diff
@@ -473,18 +473,15 @@ QUnit.test("copying with assign() excludes special keys", function() {
...
+		"existing": "neVal"
 	};
 
 	var b = new DefineMap({
 		"existing": "oldVal"
 	});
-	assign(b, a);
+	canReflect.assignMap(b, a);
 
-	QUnit.notEqual(a.constructor, b.constructor, "Constructor prop not copied");
```
Comment (chasenlehara) [inline map/map-test.js]: Was this removed because it shouldn’t have been tested in the first place?

Comment (Aosanders) [reply map/map-test.js]: @matthewp and I removed it when we changed it to test assignments between two DefineMaps, as it wasn't deemed a realistic test.
However, since I changed it back to an assignment between a regular object and a DefineMap object it might be necessary to check against anyone attempting to assign a constructor to the DefineMap object.

Comment (Aosanders) [reply map/map-test.js]: Adding the constructor test back in broke it, but I found a few solutions with @christopherjbaker that would fix it, but we should discuss it before they're implemented to see which one you prefer.
