### PR TITLE
Fixing the incorrect use of QUnit.ok

### LINKED ISSUE #211: Fix incorrect uses of QUnit.ok
When QUnit.ok is called with incorrect arguments like QUnit.ok(m.l[0].id, 5, "correct props"); an error is thrown. See canjs/canjs#3276 for details.

### PR DESCRIPTION
**Pull request by obaidott**
Fixes incorrect usage of QUnit.ok as mentioned in canjs/canjs#3276

Closes #211

### CODE REVIEW

File: test/test.js [hunk 1]
```diff
@@ -67,7 +67,7 @@ QUnit.test("default 'observable' type prevents Type from working (#29)", functio
     });
 
     QUnit.ok( m.l[0] instanceof M, "is instance" );
-    QUnit.ok(m.l[0].id, 5, "correct props");
+    QUnit.ok(m.l[0].id, "5", "correct props");
```
Comment (phillipskevin) [inline test/test.js]: should this be `QUnit.equal`?

File: test/test.js [hunk 2]
```diff
@@ -84,7 +84,7 @@ QUnit.test("inline DefineList Type", function(){
...
```
Comment (phillipskevin) [inline test/test.js]: same.
