### PR TITLE
Get values before setting them in setup

### LINKED ISSUE #182: Getting error: setting a property that has only a getter
As reported here: https://gitter.im/canjs/canjs?at=5903464bcfec919272839c87

Still working on finding an example that shows the problem

### PR DESCRIPTION
**Pull request by bmomberger-bitovi**
Avoids breakage when the value has a replaceWith getter (which itself gets replaced with a `value` property definition on first get of the property)

fixes #182

### CODE REVIEW

File: can-define.js [hunk 1]
```diff
@@ -288,6 +288,7 @@ make = {
 		events: function(prop, getCurrent, setData, eventType) {
 			return function(newVal) {
 				if (this.__inSetup) {
+					Observation.ignore(getCurrent).call(this);
```
Comment (phillipskevin) [inline can-define.js]: do you need the `Observation.ignore`? It looks like `getCurrent` only adds an observation when not `__inSetup`.

Comment (bmomberger-bitovi) [inline can-define.js]: Honestly don't know if I do.  I was trying to avoid regressing on the observable value problem.  Let's loop in @christopherjbaker .

Comment (christopherjbaker) [inline can-define.js]: Honestly, all three of the changes in #163 were directions from @justinbmeyer and I didn't fully understand them. That was literally my first day.

Comment (phillipskevin) [inline can-define.js]: I removed the `Observation.ignore` and the test for `.value functions should not be observable` still passed, so I assumed it was being taken care of by the `if` statement in `getCurrent`, but even if I remove that `if` statement it still passes, so I'm less confident also.

Comment (christopherjbaker) [inline can-define.js]: I had noticed something similar when adding the changes. Justin had requests 3 changes, but I noticed that any 1 of them would make it pass.

Comment (bmomberger-bitovi) [inline can-define.js]: In the cases we're looking at, `getCurrent()` is a callback created by `make.read.data()`, which itself doesn't have an __inSetup check.  None of the `make.read` getters call `Observation.add` directly but I don't know what happens with, say, a compute.

Comment (phillipskevin) [inline can-define.js]: Ok, let's leave it in for now and we can fix in a future PR if this `Observation.ignore` isn't needed.
